language: node_js
node_js:
    - 4
sudo: false
branches:
    only:
        - master
matrix:
  fast_finish: true
after_success:
  # install travis-after-all script to enable running `semantic-release` after ALL build succeed
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  # run `semantic-release` exactly once after all builds pass
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
notifications:
  email: false
