language: node_js
node_js:
    - 4
sudo: false
matrix:
  fast_finish: true
after_success:
  - npm run semantic-release
notifications:
  email: false
branches:
  except:
    # Ignore Git tags created by semantic-release, like "v1.2.3"
    - /^v\d+\.\d+\.\d+$/
